name: Invoke Supabase Function

# スケジュール設定。1時間おきに実行
on:
  schedule:
    - cron: "0 * * * *"  # 1時間ごとに実行されるCRON表現
    # - cron: "*/5 * * * *"  # 5分ごとに実行されるCRON表現

jobs:
  invoke-supabase-function:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke Supabase Edge Function
        run: |
          curl -i --location --request POST 'https://oqsbagdhvyckhldxguag.supabase.co/functions/v1/fetchStockPrice' \
          --header 'Authorization: Bearer ${{ secrets.SUPABASE_API_KEY }}' \
          --header 'Content-Type: application/json' \
          --data '{"name":"Auto Fetch Stock Price"}'
